/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        /* ---- Legacy semantic tokens (remapped to Luminous Strata) ---- */
        primary: '#2c6291',
        primaryDark: '#064a77',
        primaryLight: '#cfe5ff',
        primaryBorder: '#9acbff',
        accent: '#2e7d32',
        accentLight: '#e8f5e9',
        accentBorder: '#a5d6a7',
        danger: '#ba1a1a',
        dangerLight: '#ffdad6',
        dangerBorder: '#ffb4ab',
        warning: '#8a5200',
        warningLight: '#ffefd2',
        warningBorder: '#ffd699',
        bg: '#f8f9ff',
        surface: '#ffffff',
        navBg: '#ffffff',
        navActive: '#e5eeff',
        border: '#dbe6f7',
        borderLight: '#e9f0fb',
        text: '#0c1c2e',
        textSecondary: '#444748',
        textLight: '#63696b',

        /* ---- Luminous Strata palette ---- */
        'surface-dim': '#cbdbf4',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d4e4fc',
        'on-surface': '#0c1c2e',
        'on-surface-variant': '#444748',
        outline: '#747878',
        'outline-variant': '#c4c7c8',
        tertiary: '#2c6291',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#cfe5ff',
        'tertiary-fixed-dim': '#9acbff',
        'on-tertiary-fixed': '#001d34',
        'on-tertiary-fixed-variant': '#064a77',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
      },
      boxShadow: {
        soft: '0 4px 30px rgba(60, 75, 95, 0.04)',
        lift: '0 10px 40px rgba(60, 75, 95, 0.06)',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
      },
    },
  },
  plugins: [],
};
