import { NextRequest, NextResponse } from 'next/server';
import bcrypt from 'bcryptjs';
import getDb from '@/lib/db';
import { requireRole } from '@/lib/api-auth';
import { generatePassword } from '@/lib/generatePassword';
import { sendCredentialsEmail } from '@/lib/email';

const ROLE_LABEL: Record<string, string> = { teacher: 'Faculty', guardian: 'Guardian', student: 'Student', management: 'Admin' };

export async function GET(req: NextRequest) {
  const auth = await requireRole('management');
  if ('error' in auth) return auth.error;
  const role = req.nextUrl.searchParams.get('role') || '';
  const db = getDb();
  const users = (
    role
      ? await db
          .prepare('SELECT id, username, name, role, mobile, email, active, created_at FROM users WHERE role = ? AND school_id = ? ORDER BY name')
          .all(role, auth.session.schoolId)
      : await db
          .prepare(
            "SELECT id, username, name, role, mobile, email, active, created_at FROM users WHERE role NOT IN ('superadmin') AND school_id = ? ORDER BY role, name"
          )
          .all(auth.session.schoolId)
  ) as any[];

  const items = await Promise.all(
    users.map(async (u) => {
      if (u.role === 'teacher') {
        const batches = (await db
          .prepare(
            `SELECT b.id, b.name FROM teacher_batches tb JOIN batches b ON tb.batch_id = b.id WHERE tb.teacher_user_id = ?`
          )
          .all(u.id)) as any[];
        return { ...u, batches };
      }
      if (u.role === 'guardian') {
        const students = (await db
          .prepare(
            `SELECT s.id, s.name FROM student_guardians sg JOIN students s ON sg.student_id = s.id WHERE sg.guardian_user_id = ?`
          )
          .all(u.id)) as any[];
        return { ...u, students };
      }
      if (u.role === 'student') {
        const student = await db.prepare('SELECT id, name FROM students WHERE user_id = ?').get(u.id);
        return { ...u, student };
      }
      return u;
    })
  );

  return NextResponse.json({ items });
}

export async function POST(req: NextRequest) {
  // Any school admin (management, or the platform Owner acting as one) can
  // create logins for their own school — this used to be superadmin-only,
  // but that split doesn't match how a real school admin needs to operate
  // day to day (add a teacher, add a student, done).
  const auth = await requireRole('management');
  if ('error' in auth) return auth.error;
  const data = await req.json();

  if (!data.name || !data.role) {
    return NextResponse.json({ error: 'Name and role are required.' }, { status: 400 });
  }
  if (!['teacher', 'guardian', 'student', 'management'].includes(data.role)) {
    return NextResponse.json({ error: 'Invalid role.' }, { status: 400 });
  }

  // Username and password are optional: if left blank, the login is
  // auto-generated — username defaults to the person's email (which is then
  // required), password is their first name plus a random suffix, and both
  // get emailed to them. Typing a username/password manually still works
  // for anyone who wants to set their own.
  const username = (data.username || data.email || '').trim();
  if (!username) {
    return NextResponse.json({ error: 'Provide a username, or an email to auto-generate one.' }, { status: 400 });
  }
  const autoGenerated = !data.password;
  const plainPassword = data.password || generatePassword(data.name);

  const db = getDb();
  const existing = await db.prepare('SELECT id FROM users WHERE username = ?').get(username);
  if (existing) {
    return NextResponse.json({ error: 'Username already taken.' }, { status: 400 });
  }

  const hash = bcrypt.hashSync(plainPassword, 10);
  const result = await db
    .prepare('INSERT INTO users (username, password, role, name, mobile, email, school_id) VALUES (?, ?, ?, ?, ?, ?, ?)')
    .run(username, hash, data.role, data.name, data.mobile || null, data.email || null, auth.session.schoolId);
  const userId = result.lastInsertRowid as number;

  if (data.role === 'teacher' && Array.isArray(data.batch_ids)) {
    const stmt = db.prepare(
      'INSERT INTO teacher_batches (teacher_user_id, batch_id, school_id) VALUES (?, ?, ?) ON CONFLICT (teacher_user_id, batch_id) DO NOTHING'
    );
    for (const bid of data.batch_ids) await stmt.run(userId, bid, auth.session.schoolId);
  }
  if (data.role === 'guardian' && Array.isArray(data.student_ids)) {
    const stmt = db.prepare(
      'INSERT INTO student_guardians (student_id, guardian_user_id, school_id) VALUES (?, ?, ?) ON CONFLICT (student_id, guardian_user_id) DO NOTHING'
    );
    for (const sid of data.student_ids) await stmt.run(sid, userId, auth.session.schoolId);
  }
  if (data.role === 'student' && data.student_id) {
    await db.prepare('UPDATE students SET user_id = ? WHERE id = ?').run(userId, data.student_id);
  }

  let emailSent = false;
  let emailSkipped = false;
  if (data.email) {
    const school = (await db.prepare('SELECT name FROM schools WHERE id = ?').get(auth.session.schoolId)) as any;
    const res = await sendCredentialsEmail({
      to: data.email,
      greetingName: (data.name || '').split(' ')[0] || data.name,
      institute: school?.name || 'your institute',
      role: ROLE_LABEL[data.role] || data.role,
      username,
      password: plainPassword,
    });
    emailSent = res.ok;
    emailSkipped = !!res.skipped;
  }

  return NextResponse.json({
    id: userId,
    username,
    password: autoGenerated ? plainPassword : undefined,
    emailSent,
    emailSkipped,
  });
}
